version: '3.9'

services:
  pg_db:
    image: postgres:15
    environment:
      POSTGRES_USER: test_user1
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    # set port after starting DB
    command: postgres -c listen_addresses='*' -c port=5433

  app:
    build:
      context: .
    depends_on:
      - pg_db
    environment:
      DB_HOST: pg_db
      DB_PORT: 5433
      DB_NAME: test_db
      DB_USER: test_user1
      DB_PASSWORD: test_password # ${MY_SECRET_KEY} як альтернатива дадоати пароль в env vars